package org.xopen.gpevaluation.rcp.handler;

public class CommandIds {
	public static final String CALL_EDITOR = "org.xopen.gpevaluation.rcp.commands.callEditor";
	public static final String SCHEME_WIZARD="org.xopen.gpevaluation.rcp.commands.showSchemeWizard"; 
	public static final String EVALUATION_WIZARD="org.xopen.gpevaluation.rcp.commands.showEvaluationWizard"; 
	public static final String NEW_WIZARD="org.eclipse.ui.newWizard"; 
	public static final String LOGOUT="org.xopen.gpevaluation.rcp.commands.logout";
	public static final String AUTOGENERATED_CATEGORY_ID="org.eclipse.core.commands.categories.autogenerated";

	public static final String WIZARD_TYPE = "org.xopen.gpevaluation.rcp.commands.parameters.wizardType";
	public static final String WIZARD_TYPE_SCHEME = "SCHEME";
	public static final String WIZARD_TYPE_PRODUCTS = "PRODUCTS";
	public static final String WIZARD_TYPE_OTHER = "OTHER";
}
